version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo "Entered the pre-build phase"
      - $(aws ecr get-login  --no-include-email --region us-east-1)
  build:
    commands:
      - echo "Entered build phase"
      # project name local
     
      - mvn compile
      - mvn clean package -Dmaven.test.skip=true
      - echo " building docker image"
      - docker build -t sirargupta/authapps .
      - docker tag sirargupta/authapps 942605225521.dkr.ecr.us-east-1.amazonaws.com/pod-3-return-order-repository:pasauthtag
  post_build:
    commands:
    - echo "Entered the post-build phase"
    - docker push 942605225521.dkr.ecr.us-east-1.amazonaws.com/pod-3-return-order-repository:pasauthtag
    - printf '[{"name":"pas-auth-new-container","imageUri":"%s"}]' 942605225521.dkr.ecr.us-east-1.amazonaws.com/pod-3-return-order-repository:pasauthtag > taskdefinition.json
artifacts:
  files:
    - taskdefinition.json
